=== athill/andyhill.us/old/computers/recipes/recipes.xsd
<?xml version="1.0" ?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:annotation>
  <xsd:documentation xml:lang="en">
   Recipe schema for andyhill.us.
   Copyright 2004 andyhill.us. All rights reserved.
  </xsd:documentation>
</xsd:annotation>

<xsd:element name="recipes" type="recipesType"/>
 
<xsd:complexType name="RecipesType">
<xsd:sequence>
<xsd:element name="recipe" type="RecipeType" maxOccurs="unbounded" />
</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="RecipeType">
<xsd:sequence>
	<xsd:element name="name" type="xsd:string" />
	<xsd:element name="region">
	<xsd:simpleType>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Chinese" /> 
			<xsd:enumeration value="Japanese" /> 
			<xsd:enumeration value="Italian" /> 
			<xsd:enumeration value="French" /> 
			<xsd:enumeration value="English" /> 
			<xsd:enumeration value="Cajun" /> 
			<xsd:enumeration value="Other" /> 
  		</xsd:restriction>
	</xsd:simpleType>
  </xsd:element>
<xsd:element name="ingredients" type="IngredientsType"  />
<xsd:element name="directions" type="DirectionsType"  />
</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="IngredientsType">
<xsd:sequence>
<xsd:element name="ingredient" type="IngredientType" maxOccurs="unbounded"  />
</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="IngredientType">
<xsd:sequence>
<xsd:element name="type" type="xsd:string"  />
<xsd:element name="quantity" type="xsd:string"  />
</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="DirectionsType">
<xsd:sequence>
<xsd:element name="step" type="xsd:string" maxOccurs="unbounded" />
</xsd:sequence>
</xsd:complexType>

</xsd:schema>

=== athill/andyhill.us/old/computers/recipes/recipes.xml
<?xml version="1.0"?>
<recipes 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="recipes.xsd">
	<recipe>
		<name>Eggplant Parmesian</name>
		<region>Italian</region>
		<ingredients>
			<ingredient>
				<type>Eggplant</type>
				<quantity>2 pounds</quantity>
			</ingredient>
			<ingredient>
				<type>Salt</type>
				<quantity>1 tsp</quantity>
			</ingredient>
			<ingredient>
				<type>Eggs</type>
				<quantity>3</quantity>
			</ingredient>
			<ingredient>
				<type>Olive oil</type>
				<quantity>1/4 to 1/2 cup</quantity>
			</ingredient>
			<ingredient>
				<type>grated parmesian cheese</type>
				<quantity>1 tsp Oregano</quantity>
			</ingredient>
			<ingredient>
				<type>Sliced mozzerella</type>
				<quantity>1/4 #</quantity>
			</ingredient>
			<ingredient>
				<type>Tomato sauce</type>
				<quantity>3 cups</quantity>
			</ingredient>
		</ingredients>
		<directions>
		<step>Peel eggplant and slice into 1/8 in. slices, salt and let drain for 30 min.  Pat dry.</step>
		<step>Beat eggs wit 2 T water</step>
		<step>Dip eggplant slices into eggs and then into crumbs</step>
		<step>Heat 1/4 c. oil in large fry pan and saute eggplant slices until golden brown sides</step>
		<step>Continue cooking eggplant until all is sauteed, using additional oil if needed.</step>
		<step>Place half the eggplant slices in 9 X 13 pan, sprinkle with 1/3 parmesan, 1/2 oregano, and 1/3 mozzarella.  Cover with half the tomato sauce.  Repeat layers, top with last of parmesan and mozzarella.  Bake in preheated 350 oven 30 min, or until bubbly.</step>
		</directions>
	</recipe>
</recipes>
